### PR TITLE
changed github.com to google.com as github.com is not always pingable…

### PR DESCRIPTION
**Pull request by kurtjcu**
… (despite correct DNS)

### CODE REVIEW

**Comment by lbussy** [comment]
This is a bad idea ... we need network access to GitHub not Google.  Created #32 to properly address this.

**Comment by kurtjcu** [comment]
@lbussy code comments seem to indicate this is just a internet connection test?

**Comment by lbussy** [comment]
Sorry for my short comments - seems like I was attacking.  Not intended.  

The test is intended to provide a (rather poor) indication of whether we are going to be successful cloning from GitHub. To that end, pinging Google only tells us Google can be pinged.  It’s not GitHub and most importantly it’s not a web connection.  ICMP is way over-used as a test when it tells us little.  

My proposed PR uses wget with —spider which specifically tests a web connection to GitHub and the —spider argument does not require that any content be received making it much faster than regular wget for these purposes.  

Longer term it might just be better to capture a failure at the clone.  However, I know @Thorrak’s intent is to “set up” the installation ahead of time and allow it to run unimpeded.  This pre-test supports that strategy.

**Comment by kurtjcu** [comment]
@lbussy No problems :)
I do think there are a few things to be addressed to create a better solution

1. Using wget to test for Github in a script that is primarily curled from Github seems a little circular and smells of legacy code in need of a refactor.
2. The name of the containing function indicates it is to check for internet connection. See above comment. 

I believe that as the auto-install.sh is intended to be run from a curl command (see the README.md) this function and all reference to it should be removed. A catch in the install.sh would make for better code and the install.sh and be run manually or from the automatic install. Having code dependent on checking from a certain entry point when the code can be run from a later entry point missing this check seems like bad idea. :)

**Comment by lbussy** [comment]
> I do think there are a few things to be addressed to create a better solution

There always are.  It's a matter of where to stop. :)

> The name of the containing function indicates it is to check for internet connection. See above comment.

Does checking the result of a wget not imply a successful Internet connection?  Doing a wget tests the Internet to the actual endpoint, using TCP rather than ICMP and using the proper port.  Ping is a poor test for anything, is part of the "legacy" of the original scripts, and should never have been used.  I want to beat my system engineers who answer "well, ping worked" when I ask them if there are ACLs blocking their application.

>> Using wget to test for Github in a script that is primarily curled from Github seems a little circular and smells of legacy code in need of a refactor.

Maybe ... but people also clone a repo and then run it, etc.  This particular script is not curled.  auto-install.sh is the one to which install.fermentrack.com redirects and is curled; this (install.sh) is run after that clones the repo.  If you look at auto-install.sh, ping is not found.  This script also supports command line options (sort of by default NOT curled in) to allow switching branches, etc.  Therefore checking that GitHub is available is a good idea because it's not _just_ for initial install.

The thing is, the longer I work on BrewPi (remix) the more I realize people will find new, unique, and sometimes amazing ways to do things wrong.  We catch them when we can.

**Comment by thorrak** [comment]
THANK YOU BOTH for the work on these two pull requests to fix the installation issues!

**Comment by thorrak** [comment]
I think I ended up effectively merging all these changes separately from this PR. Closing the PR to clean things up.

Thanks again!

**Pull request closed without merging**
